version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.23.7
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50051:50051" # optional, bisa dihilangkan kalau belum pakai gRPC
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
